# TorXakis - Model Based Testing
# Copyright (c) 2015-2017 TNO and Radboud University
# See LICENSE at root directory of this repository.

build: off
skip_non_tags: true

version: b{build}
# branches:
    # only:
    # - develop
    # - /^hotfix.*$/

init:
- ps: $buildVersion = $env:APPVEYOR_REPO_TAG_NAME.TrimStart("v")
- ps: Update-AppveyorBuild -Version "${buildVersion}_${env:APPVEYOR_BUILD_NUMBER}"
- ps: $STACK = "C:\SourceWindowsInstaller\.stack"
- mkdir %LOCALAPPDATA%\Programs\stack
- mkdir %LOCALAPPDATA%\Programs\stack\x86_64-windows

install:
- ps: if (-not (Test-Path $STACK)) { mkdir $STACK } else { Write-Host "${STACK} found." }
# obtain the stack executable
- ps: |
    if (-not (Test-Path "$STACK\stack.exe")) {
        curl -Verbose -OutFile stack.zip https://github.com/commercialhaskell/stack/releases/download/v2.1.3/stack-2.1.3-windows-x86_64.zip
        7z x $("-o" + $STACK) stack.zip stack.exe
    } else {
        Write-Host "stack.exe found.";
    }
- choco install wixtoolset --version 3.11.2
- refreshenv
- ps: $env:Path += ";C:\Program Files\Git\mingw64\bin;${STACK};C:\Users\appveyor\AppData\Roaming\local\bin"

before_build:
- ps: $env:BUILD_VERSION = $buildVersion

build_script:
- .\TxsCreateInstaller.bat %BUILD_VERSION% .\wxs.config
# - ps: tree $env:APPVEYOR_REPO_TAG_NAME

# after_build:
# -

# before_test:
# -

clone_folder: c:\SourceWindowsInstaller
environment:
  global:
    STACK_ROOT: c:\SourceWindowsInstaller\.stack

cache:
- .stack
- '%LOCALAPPDATA%\Programs\stack\x86_64-windows\ghc-integersimple-8.2.2'
# in case the installation folder was not retrieved from cache
- '%LOCALAPPDATA%\Programs\stack\x86_64-windows\ghc-integersimple-8.2.2.installed -> %LOCALAPPDATA%\Programs\stack\x86_64-windows\ghc-integersimple-8.2.2\bin\ghcii.sh'
- '%LOCALAPPDATA%\Programs\stack\x86_64-windows\msys2-20180531'
# in case the installation folder was not retrieved from cache
- '%LOCALAPPDATA%\Programs\stack\x86_64-windows\msys2-20180531.installed -> %LOCALAPPDATA%\Programs\stack\x86_64-windows\msys2-20180531\autorebase.bat'
# - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

# test_script:
# -

# after_test:

artifacts:
- path: $(APPVEYOR_REPO_TAG_NAME)\WindowsInstaller\TorXakis.msi
  name: installer

deploy:
- provider: GitHub
  artifact: installer
  draft: true
  description: ''
  auth_token:
    secure: X18bNvTEaVreQSwPS5og9eYv7YHG3u5QvzotRArepctUl1gXtJCIPGbTMQiwcj4b
  repository: TorXakis/TorXakis
  on:
    appveyor_repo_tag: true
